### ISSUE TITLE
document.registerElement is deprecated and will be removed in M80

### ISSUE THREAD

**Issue by likegeo** [KonsomeJona/electron-localizer#1]
As i see registerElement will be removed on february  2020, what is the alternative of registerElement? 

[Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

I tried use window.customElements.define but get this error:

`Uncaught TypeError: Failed to execute 'define' on 'CustomElementRegistry': The callback provided as parameter 2 is not a function.`

**Comment by KonsomeJona** [comment]
It's going to require few changes but here is a snippet:

```
class LocalizedTextElement extends HTMLElement {
    constructor() {
        super();
    }

    connectedCallback() {
        var key = this.hasAttribute('key') ? this.getAttribute('key') : ''; 
        this.innerHTML = getLocalizedText(key); // implement your own getLocalizedText function to fetch localized text from a dict
    }
}

customElements.define('localized-text', LocalizedTextElement);
```

In your HTML page:
`<localized-text text="my_localized_text"></localized-text>`

**Comment by KonsomeJona** [comment]
Fixed with last commit removing dependency with Electron and registerElement deprecated API.
